Remove /dev/log after syslog is shutdown
On SUSE15 at least, /dev/log is a symlink to /run/systemd/journal/dev-log. With WW's initrd /dev/log socket left over, this symlink is never created and /dev/log isn't usable, eg:

```
logger: socket /dev/log: Connection refused
```

Conflicts:
	provision/initramfs/init

diff --git a/provision/initramfs/init b/provision/initramfs/init
--- a/provision/initramfs/init
+++ b/provision/initramfs/init
@@ -548,6 +548,9 @@ if [ -x "$NEWROOT/sbin/init" -o -h "$NEWROOT/sbin/init" ]; then
         wwfailure
     fi
 
+    # Cleanup /dev/log from devtmpfs
+    rm -f /dev/log >/dev/null 2>&1 || true
+
     if [ -n "$WWPOSTNETDOWN" ]; then
         NETDEV=`cat /tmp/wwdev`
         if [ -f "/tmp/ifcfg-$WWNETDEV" ]; then
